displayName=League Pings
author=Pooploop206
description=A plugin to allow players in the same party to ping in the style of League of Legends pings
tags=pings,ping,party
plugins=com.lolpings.LolPingsPlugin